#spring:
 # data:
  #  mongodb:
      # In Case of mongodb Repel Set
      #uri: mongodb://${MONGO_DB_HOSTNAME}:${MONGO_DB_PASSWORD}@mongod-0.mongodb:27017,mongod-1.mongodb:27017,mongod-2.mongodb:27017/users
     # host: svc-1
     # port: 27017
    #  username: ${MONGO_DB_USERNAME}                                
     # password: ${MONGO_DB_PASSWORD}
    # database: test
    #  authentication-database: admin

#server:
 # port: 8080           

spring:
  data:
    mongodb:
      host: svc-1
      port: 27017
      database: test

server:
  port: 8080
 
